export const GET_WEATHER_DATA_LOADING = "GET_WEATHER_DATA_LOADING";
export const GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS";
export const GET_WEATHER_DATA_FAIL = "GET_WEATHER_DATA_FAIL";

export const GET_LAT_LON_WEATHER_DATA_SUCCESS =
  "GET_LAT_LON_WEATHER_DATA_SUCCESS";
export const GET_LAT_LON_WEATHER_DATA_FAIL = "GET_LAT_LON_WEATHER_DATA_FAIL";
